import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/Navbar";

const dmSans = DM_Sans({
  weight: ["500"],
  style: "normal",
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
